### PR TITLE
Override config via cssh_* environment variables

### PR DESCRIPTION
**Pull request by babs**
Allow runtime configuration override via environment variables

### CODE REVIEW

**Comment by pevik** [comment]
Environment variables are usually upper case. Although that might be confusing, when cssh config variables are lower case.

**Comment by babs** [comment]
I usually apply uppercase standard too.
And I also had the same way of thought as you about confusion on case regarding config variable.
Give me few minutes... :D

**Comment by babs** [comment]
@pevik here it is :)

**Comment by pevik** [comment]
You actually have mistakes in both commits, have look in my branch:
https://github.com/pevik/clusterssh/commits/override_via_env.fixes

**Comment by babs** [comment]
No, I think you're mistaken.

env_config_key contains the key, not the value.

ie: let's take configuration key screen_reserve_left, at first  env_config_key contains cssh_screen_reserve_left, as ENVIRONMENT key, then it's tested to see an upper version of this exists in ENV hash. if it's the case, the key is converted to uppercase.

Once done, the key is once again checked aginst the ENV hash, if it exists, it takes the env value referenced by the prefixed key to the actual configuration key, _without prefix_

**Comment by babs** [comment]
You're right. Let me fix it

**Comment by babs** [comment]
Feature commits has been squashed.

**Comment by pevik** [comment]
Yep, working now :).
```
Reviewed-by: Petr Vorel <pvorel@suse.cz>
Tested-by: Petr Vorel <pvorel@suse.cz>
```

**Pull request merged**
